config: 
  - site1: "availability.json"
  - site2: "availability.json"
  - site3: "availability.json"

site1:
  - name: "Demo Availability Site 1"
  - location: "GEOLOCATION-9999453BE4BDB3CD"
  - host: "https://www.azure.com"

site2:
  - name: "Demo Availability Site 2"
  - location: "GEOLOCATION-9999453BE4BDB3CD"
  - host: "https://www.dynatrace.com"

site3:
  - name: "Demo Availability Site 3"
  - location: "GEOLOCATION-9999453BE4BDB3CD"
  - host: "https://www.microsoft.com"