# requires the following secrets:
# DT_BASE_URL
# DT_API_TOKEN 
# AZURE_CREDENTIALS

name: Deploy Order Service
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      order-version:
        description: 'Order Service Version'     
        required: true
        default: '1'
  repository_dispatch:
    types: 
      - deploy1
      - deploy2
env:
  REGISTRY_NAME: dtdemos
  CLUSTER_NAME: jahn-aks-demo
  CLUSTER_RESOURCE_GROUP: jahn-aks-demo
  NAMESPACE: staging
  FEATURE_NUMBER: '1'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master
      
    - name: "Set new feature number"
      run: |
        if [ "${{ github.event.action == 'deploy1' }} ];then
          FEATURE_NUMBER='1'
        elif [ "${{ github.event.action == 'deploy2' }} ];then
          FEATURE_NUMBER='2'
        elif [ -z ${{ github.event.inputs.order-version }};then
          FEATURE_NUMBER=${{ github.event.inputs.order-version }}
        else
          echo "Missing FEATURE_NUMBER argument"
          exit 1
        fi
      
    - name: Update order-service.yml
      run: |
        echo "Setting feature to $NEW_VERSION"
        MANIFEST_FILE=manifests/order-service.yml
        sed -ie "s|version: .*$|version: \"${{ github.event.inputs.order-version }}\"|" $MANIFEST_FILE
        sed -ie "s|image: dtdemos/dt-orders-order-service:.*$|image: dtdemos/dt-orders-order-service:${{ github.event.inputs.order-version }}|" $MANIFEST_FILE
        cat $MANIFEST_FILE

    - name: "Set the target AKS cluster"
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - name: "Deploy order-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/order-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-order-service:${{ github.event.inputs.order-version }}

    - name: "Dynatrace Deployment Event Order Service"
      uses: dynatrace-oss/dynatrace-github-action@v7
      with:
        url: '${{ secrets.DT_BASE_URL }}'
        token: '${{ secrets.DT_API_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy order version ${{ github.event.inputs.order-version }}"
            deploymentVersion: "${{ github.event.inputs.order-version }}"
            deploymentProject: "dt-orders"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - PROCESS_GROUP_INSTANCE:service:order
            dimensions:
              project: "${{ github.repository }}"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"
          
