# requires the following secrets:
# DT_URL
# DT_TOKEN 
# AZURE_CREDENTIALS

name: Deploy all
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      order-version:
        description: 'Order Service Version'     
        required: true
        default: '1'
      customer-version:
        description: 'Customer Service Version'     
        required: true
        default: '1'
env:
  REGISTRY_NAME: dtdemos
  CLUSTER_NAME: jahn-aks-demo
  CLUSTER_RESOURCE_GROUP: jahn-aks-demo
  NAMESPACE: dt-orders
  FRONTEND_VERSION: 1
  CATALOG_VERSION: 1

jobs:
  setup-build-publish-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master
    - name: "Set the target AKS cluster"
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    - name: "Create namespace if doesn't exist"
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -

    - name: "Deploy frontend"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/frontend.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-frontend:${{ env.FRONTEND_VERSION }}

    - name: "Dynatrace Deployment Event frontend"
      uses: dynatrace-oss/dynatrace-github-action@v6
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy frontend version ${{ env.FRONTEND_VERSION }}"
            deploymentVersion: "${{ env.FRONTEND_VERSION }}"
            deploymentProject: "${{ github.repository }}"
            remediationAction: "None"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - PROCESS_GROUP_INSTANCE:service:frontend
            dimensions:
              project: "dt-orders"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"

    - name: "Deploy customer-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/customer-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-customer-service:${{ github.event.inputs.customer-version }}

    - name: "Dynatrace Deployment Event Customer Service"
      uses: dynatrace-oss/dynatrace-github-action@v6
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy frontend version ${{ github.event.inputs.customer-version }}"
            deploymentVersion: "${{ github.event.inputs.customer-version }}"
            deploymentProject: "${{ github.repository }}"
            remediationAction: "None"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - PROCESS_GROUP_INSTANCE:service:frontend
            dimensions:
              project: "dt-orders"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"

    - name: "Deploy catalog-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/catalog-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-catalog-service:${{ env.CATALOG_VERSION }}

    - name: "Dynatrace Deployment Event Catalog Service"
      uses: dynatrace-oss/dynatrace-github-action@v6
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - title: "Deploy catalog-service version ${{ env.CATALOG_VERSION }}"
            type: CUSTOM_INFO
            description: "Deploy catalog-service version ${{ env.CATALOG_VERSION }}"
            source: GitHub
            tags:
              - SERVICE:service:catalog
            dimensions:
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
              owner: ${{ github.repository_owner }}
              github-job: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"

    - name: "Deploy order-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/order-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-order-service:${{ github.event.inputs.order-version }}

    - name: "Dynatrace Deployment Event Order Service"
      uses: dynatrace-oss/dynatrace-github-action@v6
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy frontend version ${{ github.event.inputs.order-version }}"
            deploymentVersion: "${{ github.event.inputs.order-version }}"
            deploymentProject: "${{ github.repository }}"
            remediationAction: "None"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - PROCESS_GROUP_INSTANCE:service:frontend
            dimensions:
              project: "dt-orders"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"

    - name: "Deploy load-traffic"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/load-traffic.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-load:1

    - name: "Deploy browser-traffic"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/browser-traffic.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-browser:1