# requires the following secrets:
# DT_BASE_URL
# DT_API_TOKEN 
# AZURE_CREDENTIALS

name: Deploy Order Service
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      order-version:
        description: 'Order Service Version'     
        required: true
        default: '1'
  repository_dispatch:
    types: 
      - deploy

env:
  REGISTRY_NAME: dtdemos
  CLUSTER_NAME: jahn-aks-demo
  CLUSTER_RESOURCE_GROUP: jahn-aks-demo
  NAMESPACE: staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master
      
    - name: "Set new feature number"
      run: |
        if [ ! -z ${{ github.event.inputs.order-version }} ];then
          echo "inputs.order-version = ${{ github.event.inputs.order-version }}"
          version_num="${{ github.event.inputs.order-version }}"
        elif [ "${{ github.event.action }}" = "deploy" ];then
          version_num="${{ github.event.client_payload.version }}"
          echo "webhook triggered version $version_num"
        else
          echo "Missing version number argument"
          exit 1
        fi
        
        echo "Setting version_num=$version_num"
        echo "version_num=$version_num" >> $GITHUB_ENV

    - name: Update order-service.yml
      run: |
        echo "Setting manifest version to ${{ env.version_num }}"

        MANIFEST_FILE=manifests/order-service.yml
        sed -ie "s|version: .*$|version: \"${{ env.version_num }}\"|" $MANIFEST_FILE
        sed -ie "s|image: dtdemos/dt-orders-order-service:.*$|image: dtdemos/dt-orders-order-service:${{ env.version_num }}|" $MANIFEST_FILE
        cat $MANIFEST_FILE

    - name: "Set the target AKS cluster"
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - name: "Deploy order-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/order-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-order-service:${{ env.version_num }}

    - name: "Dynatrace Deployment Event Order Service"
      uses: dynatrace-oss/dynatrace-github-action@v7
      with:
        url: '${{ secrets.DT_BASE_URL }}'
        token: '${{ secrets.DT_API_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy order version ${{ env.version_num }}"
            deploymentVersion: "${{ env.version_num }}"
            deploymentProject: "dt-orders"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - PROCESS_GROUP_INSTANCE:service:order
            dimensions:
              project: "${{ github.repository }}"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"
          
