# requires the following secrets:
# DT_BASE_URL
# DT_API_TOKEN 
# AZURE_CREDENTIALS

name: Deploy Order Service
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      order-version:
        description: 'Order Service Version'     
        required: true
        default: '1'
env:
  REGISTRY_NAME: dtdemos
  CLUSTER_NAME: jahn-aks-demo
  CLUSTER_RESOURCE_GROUP: jahn-aks-demo
  NAMESPACE: dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master

    - name: "Set the target AKS cluster"
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - name: "Create k8 namespace"
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -

    - name: "Create k8 rolebinding for dt k8 dashboard"
      run: |
        kubectl -n dev delete rolebinding default-view 
        kubectl -n dev create rolebinding default-view --clusterrole=view --serviceaccount=dev:default

    - name: "Deploy order-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/order-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-order-service:${{ github.event.inputs.order-version }}

    - name: "Dynatrace Deployment Event Order Service"
      uses: dynatrace-oss/dynatrace-github-action@v7
      with:
        url: '${{ secrets.DT_BASE_URL }}'
        token: '${{ secrets.DT_API_TOKEN }}'
        events: |
          - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy order version ${{ github.event.inputs.order-version }}"
            deploymentVersion: "${{ github.event.inputs.order-version }}"
            deploymentProject: "dt-orders"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - PROCESS_GROUP_INSTANCE:service:order
            dimensions:
              project: "${{ github.repository }}"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"
        - type: CUSTOM_DEPLOYMENT
            source: GitHub
            deploymentName: "Deploy order version ${{ github.event.inputs.order-version }}"
            deploymentVersion: "${{ github.event.inputs.order-version }}"
            deploymentProject: "dt-orders"
            ciBackLink: "https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"
            tags:
              - SERVICE:service:order
            dimensions:
              project: "${{ github.repository }}"
              repository-owner: ${{ github.repository_owner }}
              repository: "https://github.com/${{ github.repository }}"
              repository-branch: "${{ github.ref }}"