name: Deploy to AKS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      customer-version:
        description: 'Customer Service Version'     
        required: true
        default: '1'
env:
  REGISTRY_NAME: dtdemos
  CLUSTER_NAME: jahn-aks-demo
  CLUSTER_RESOURCE_GROUP: jahn-aks-demo
  NAMESPACE: dt-orders
  
jobs:
  setup-build-publish-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master
    - name: "Set the target AKS cluster"
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    - name: "Create namespace if doesn't exist"
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    - name: "Deploy frontend"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/frontend.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-frontend:1.0.0
    - name: "Dynatrace Deployment Event frontend"
      uses: dynatrace-oss/dynatrace-github-action@v5
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - title: "Deploy frontend version 1"
            type: CUSTOM_INFO
            description: "Deploy frontend version 1"
            source: GitHub
            tags:
              - SERVICE:service:frontend
            dimensions:
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
            owner: ${{ github.repository_owner }}
    - name: "Deploy customer-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/customer-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-customer-service:${{ github.event.inputs.customer-version }}
    - name: "Dynatrace Deployment Event Customer Service"
      uses: dynatrace-oss/dynatrace-github-action@v5
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - title: "Deploy customer-service version ${{ github.event.inputs.customer-version }}"
            type: CUSTOM_INFO
            description: "Deploy customer-service version ${{ github.event.inputs.customer-version }}"
            source: GitHub
            tags:
              - SERVICE:service:customer
            dimensions:
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
            owner: ${{ github.repository_owner }}
    - name: "Deploy catalog-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/catalog-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-catalog-service:1.0.0
    - name: "Dynatrace Deployment Event Catalog Service"
      uses: dynatrace-oss/dynatrace-github-action@v5
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - title: "Deploy catalog-service version 1"
            type: CUSTOM_INFO
            description: "Deploy catalog-service version 1"
            source: GitHub
            tags:
              - SERVICE:service:catalog
            dimensions:
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
            owner: ${{ github.repository_owner }}
    - name: "Deploy order-service"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/order-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-order-service:1.0.0
    - name: "Dynatrace Deployment Event Order Service"
      uses: dynatrace-oss/dynatrace-github-action@v5
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.DT_TOKEN }}'
        events: |
          - title: "Deploy order-service version 1"
            type: CUSTOM_INFO
            description: "Deploy order-service version 1"
            source: GitHub
            tags:
              - SERVICE:service:order
            dimensions:
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
            owner: ${{ github.repository_owner }}
    - name: "Deploy load-traffic"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/load-traffic.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-load:1.0.0
    - name: "Deploy browser-traffic"
      uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/browser-traffic.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-browser:1.0.0