name: SLO Evaluation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  KEPTN_PROJECT: "dynatrace",
  KEPTN_SERVICE: "journeyservice",
  KEPTN_STAGE: "quality-gate"
jobs:
  slo-evaluation:
    name: Evaluation
    runs-on: ubuntu-latest
    steps:
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@feature/keptn-context-as-output
      with:
        keptnApiUrl: ${{ secrets.KEPTN_API_URL }}
        keptnApiToken: ${{ secrets.KEPTN_API_TOKEN }}
        event: |
          {
            "data": {
              "evaluation": {
                "end": "2021-05-01T00:02:00.000Z",
                "start": "2021-05-01T00:00:00.000Z"
              },
              "project": ${{ env.KEPTN_PROJECT }},
              "service": ${{ env.KEPTN_SERVICE }},
              "stage": ${{ env.KEPTN_STAGE }}
            },
            "source": "https://keptn.keptn-demo.alliances.dynatracelabs.com",
            "specversion": "1.0",
            "type": "sh.keptn.event.quality-gate.evaluation.triggered",
            "shkeptnspecversion": "0.2.1"
          }
    - name: Show keptnContext
      run: echo "The keptnContext is ${{ steps.send-keptn-event.outputs.keptnContext }}"
    - name: Show keptn Bridge URL
      run: echo "https://${{ secrets.KEPTN_API_URL }}/bridge/evaluation/${{ steps.send-keptn-event.outputs.keptnContext }}/${{ env.KEPTN_STAGE }}"