name: Deploy to AKS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  REGISTRY_NAME: dtdemos
  CLUSTER_NAME: jahn-aks-demo
  CLUSTER_RESOURCE_GROUP: jahn-aks-demo
  NAMESPACE: dt-orders
  
jobs:
  setup-build-publish-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get code from github repo"
      uses: actions/checkout@master
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    - uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/frontend.yml
          manifests/service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-frontend:1.0.0
    - uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/customer-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-customer-service:1.0.0
    - uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/catalog-service.yml
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-catalog-service:1.0.0
    - uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/load-traffic
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-load:1.0.0
    - uses: azure/k8s-deploy@v1.4
      with:
        namespace: ${{ env.NAMESPACE }}
        action: deploy
        manifests: |
          manifests/browser-traffic
        images: |
          ${{ env.REGISTRY_NAME }}/dt-orders-browser:1.0.0