# requires the following secrets:
# KEPTN_API_URL
# KEPTN_API_TOKEN 

name: SLO Evaluation
on:
  workflow_dispatch:

env:
  EVALUATION_RULE: pass_on_warning
  KEPTN_PROJECT: dt-orders
  KEPTN_SERVICE: catalog
  KEPTN_STAGE: dev
  LABELS: "runId=${{ github.run_id }},executedBy=GitHub,Job=https://github.com/dt-demos/github-actions/actions/runs/${{ github.run_id }}"            
  #START: "2021-06-09T21:00:00"
  #END: "2021-06-09T22:00:00"
  TIMEFRAME: 5m
  DEBUG: true
  KEPTN_BASE_URL: https://rob00334.cloudautomation.live.dynatrace.com


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dtdemos/keptn-automation:1
      env:
        EVALUATION_RULE: ${{ env.EVALUATION_RULE }}
        KEPTN_BASE_URL: ${{ env.KEPTN_BASE_URL }}
        KEPTN_API_TOKEN: ${{ secrets.KEPTN_API_TOKEN }}
        KEPTN_PROJECT: ${{ env.KEPTN_PROJECT }}
        KEPTN_SERVICE: ${{ env.KEPTN_SERVICE }}
        KEPTN_STAGE: ${{ env.KEPTN_STAGE }}
        SOURCE: ${{ env.SOURCE }}
        LABELS: ${{ env.LABELS }}
        START: ${{ env.START }}
        END: ${{ env.END }}
        TIMEFRAME: ${{ env.TIMEFRAME }}
        DEBUG: ${{ env.DEBUG }}

    steps:
      - name: keptn get project
        run: keptn.sh get project
      - name: SLO Evaluation
        run: slo-evaluation.sh
