# requires the following secrets:
# DT_BASE_URL
# DT_API_TOKEN 

name: Monaco Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dynatraceace/monaco-runner:release-v1.5.3
      env:
        DT_BASEURL: ${{ secrets.DT_BASE_URL }}
        DT_API_TOKEN: ${{ secrets.DT_API_TOKEN }}
        NEW_CLI: "1"
    steps:
      # github automatically creates a volume to the checked out code
      # so we can reference them via ./foldername
      - uses: actions/checkout@v2
      
      - name: Monaco version
        run: monaco --version 

      - name: Run Monaco
        run:  monaco deploy -v --environments ./monaco/environments.yml --project dt-orders ./monaco/projects
