# This is a basic workflow to help you get started with Actions

name: Monaco Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dynatraceace/monaco-runner:release-v1.5.0
      env:
        DT_BASEURL: ${{ secrets.DT_URL }}
        DT_API_TOKEN: ${{ secrets.DT_TOKEN }}
        NEW_CLI: "1"
    steps:
      - uses: actions/checkout@v2
      - name: Monaco version
        run: monaco --version 
      - name: List files
        run: ls -l
      - name: pwd
        run: pwd
      - name: Run Monaco
        run:  monaco deploy -v --environments monaco/environments.yml --project dt-orders monaco/projects
