# This is a basic workflow to help you get started with Actions

name: Monaco Test

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: dynatraceace/monaco-runner:release-v1.5.0
      #options: -v /__w/actions-test-repo/actions-test-repo:/zap/wrk/:rw

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build count
        run: monaco --version 
        