# requires the following secrets:
# DT_URL
# DT_TOKEN 

name: Test Dynatrace OSS Action
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test CUSTOM_DEPLOYMENT
        uses: dynatrace-oss/dynatrace-github-action@v7
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          events: |
            - type: CUSTOM_DEPLOYMENT
              source: GitHub
              deploymentName: "CUSTOM_DEPLOYMENT deploymentName to SERVICE"
              deploymentProject: "CUSTOM_DEPLOYMENT deploymentProject"
              remediationAction: "CUSTOM_DEPLOYMENT remediationAction"
              ciBackLink: "https://www.dyntrace.com"
              deploymentVersion: "123"
              tags:
                - SERVICE:service:order
              dimensions:
                project: "dt-orders"
                repository-owner: ${{ github.repository_owner }}
                repository: "https://github.com/${{ github.repository }}"
                repository-branch: "${{ github.ref }}"
            - type: CUSTOM_DEPLOYMENT
              source: GitHub
              deploymentName: "CUSTOM_DEPLOYMENT deploymentName to PROCESS_GROUP_INSTANCE"
              deploymentProject: "CUSTOM_DEPLOYMENT deploymentProject"
              remediationAction: "CUSTOM_DEPLOYMENT remediationAction"
              ciBackLink: "https://www.dyntrace.com"
              deploymentVersion: "123"
              tags:
                - PROCESS_GROUP_INSTANCE:service:order
              dimensions:
                project: "dt-orders"
                repository-owner: ${{ github.repository_owner }}
                repository: "https://github.com/${{ github.repository }}"
                repository-branch: "${{ github.ref }}"
            - title: "CUSTOM_INFO title"
              type: CUSTOM_INFO
              description: "CUSTOM_INFO description"
              source: GitHub
              tags:
                - SERVICE:service:order
          metrics: |
            - metric: "github.metric1"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: "${{ github.repository_owner }}"
            - metric: "github.build.total"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: "${{ github.repository_owner }}"
            - metric: "github.build.success"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: "${{ github.repository_owner }}"
